FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . /app

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "payment_server:app", "-b", "0.0.0.0:8000"]
